\documentclass{article}
\input{../config/commontex}

\title{Installation of a local ACNUC socket server and of a local ACNUC database on your machine.}
\author{Penel, S.}

\begin{document}
\SweaveInput{../config/commonrnw.rnw}
\maketitle
\tableofcontents
% BEGIN - DO NOT REMOVE THIS LINE



%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction}
%%%%%%%%%%%%%%%%%%%%%%%

This chapter is under development.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{System requirement}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Basically if you are installing \Rlogo{} from the
sources, you should be able to build a ACNUC socket server.
The socket server will build under a number of common Unix and Unix-alike
platforms. You will need several tools: programs are written in C thus 
you will need a
means of compiling C (as gcc compilation tools for linux or unix, Apple
Developer Tools  for MacOSX). You need as well library zlib and sockets
(standards on linux and unix).


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Setting a local ACNUC database to be queried by the server}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

First of all yo need an ACNUC database, built by yourself or  downloaded from the PBIL ftp server.
An ACNUC database is composed of two sets of files:
\begin{enumerate}
	\item  the acnuc index files.
	\item  the database files (\textit{i.e.} flat files in EMBL/GenBank or SwissProt format).
\end{enumerate}

These two sets will be located  in the \texttt{index} and  \texttt{flat\_files} directories  respectively.

An example of an ACNUC database is available on the PBIL ftp server  at this url:
\url{ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/acnucdatabase.tar.Z}.
 
You may install the database as it follows:
Let \texttt{ACNUC\_HOME} be the base directory for ACNUC installation.

<<makeACNUCHOME,fig=F,eval=T>>=
dir.create("./ACNUC_HOME", showWarning = FALSE)
@ 


Let ACNUC\_HOME/ACNUC\_DB be the  directory where you want to install the databases and ACNUC\_HOME/ACNUC\_DB/demoacnuc 
the directory where you want to install the demo database.

<<makeACNUCHOMEdemo,fig=F,eval=T>>=
dir.create("./ACNUC_HOME/ACNUC_DB", showWarning = FALSE)
dir.create("./ACNUC_HOME/ACNUC_DB/demoacnuc", showWarning = FALSE)
@ 


\begin{itemize}
\item Dowload the ACNUC database in the ./ACNUC\_HOME/ACNUC\_DB/demoacnuc/ directory.

% Mettre eval=F apres premier download
<<dowloadacnucdemo,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/acnucdatabase.tar.Z",
destfile = "./ACNUC_HOME/ACNUC_DB/demoacnuc/acnucdatabase.tar.Z")
@ 


\item Uncompress and untar the \texttt{acnucdatabase.tar.Z} file 

<<decompressacnuc,fig=F,eval=T>>=
pwd <- getwd()
setwd("./ACNUC_HOME/ACNUC_DB/demoacnuc/")
system("gunzip -f acnucdatabase.tar.Z")
system("tar -xvf acnucdatabase.tar")
system("rm -f acnucdatabase.tar")
setwd(pwd)
@ 

\end{itemize}
Now you sould get the following directories:
\begin{verbatim}
ACNUC_HOME/ACNUC_DB/demoacnuc/index
ACNUC_HOME/ACNUC_DB/demoacnuc/flat_files
\end{verbatim}

The directory \texttt{ACNUC\_HOME/ACNUC\_DB/demoacnuc} contains: 
<<showacnuchomecontent,fig=F,eval=T>>=
dir("./ACNUC_HOME/ACNUC_DB/demoacnuc")
@ 

These directories contain respectively:

<<showacnuchomecontent2,fig=F,eval=T>>=
dir("./ACNUC_HOME/ACNUC_DB/demoacnuc/index")
dir("./ACNUC_HOME/ACNUC_DB/demoacnuc/flat_files")
@ 


This database contains the complete genome of \textit{Escherichia coli} 
K12 W3110 and \textit{Saccharomyces cerevesiae}.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Build the ACNUC sockets server from the sources.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Once you have a local  ACNUC database available on your server you need to install the sockets server.

\subsection{Download the sources.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The code source of the racnucd server is available on the PBIL server  at this url:
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/racnucd.html
\end{verbatim}
Alternatively you can download directly  the source from the ftp at:
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/racnucd.tar
\end{verbatim}

\subsection{Build the ACNUC sockets server.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

You may install the racnucd server as it follows:
let ACNUC\_HOME/ACNUC\_SOFT/ be the base directory for the ACNUC softs.

<<makeRACNUCCDHOME,fig=F,eval=T>>=
dir.create("./ACNUC_HOME/ACNUC_SOFT", showWarning = FALSE)
@

\begin{itemize}
\item Dowload the \texttt{racnucd.tar} file into ACNUC\_HOME/ACNUC\_SOFT.

% Mettre eval=F apres premier download
<<dowloadracnucd,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/racnucd.tar",
destfile = "./ACNUC_HOME/ACNUC_SOFT/racnucd.tar")
@

\item Untar the \texttt{racnucd.tar} file 

<<decompressacnuc,fig=F,eval=T>>=
setwd("./ACNUC_HOME/ACNUC_SOFT/")
system("tar -xvf racnucd.tar")
system("rm -f racnucd.tar")
setwd(pwd)
@ 

\end{itemize}
Now you sould get the following directory:


<<checkracnucd,fig=F,eval=T>>=
dir("./ACNUC_HOME/ACNUC_SOFT/")
dir("./ACNUC_HOME/ACNUC_SOFT/racnucd/")
@ 

Go into \texttt{ACNUC\_HOME/ACNUC\_SOFT/racnucd/} and type \texttt{make}.
This should create the \textbf{racnucd} executable.

<<makeracuc,fig=F,eval=T>>=
setwd("./ACNUC_HOME/ACNUC_SOFT/racnucd")
system("make")
dir(pattern = "racnucd")
setwd(pwd)
@ 

\subsection{Setting the ACNUC sockets server.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The server is configured by several parameters described in a configuration file \textbf{racnuc.ini}.
The \textbf{racnucd.ini} file is structued as follows:


<<showmeracnunini,fig=F,eval=T>>=
cat(readLines("./ACNUC_HOME/ACNUC_SOFT/racnucd/racnucd.ini"), sep = "\n")
@ 

\begin{itemize}
\item \textbf{port} is the port of the socket server 
\item \textbf{maxtimle} is the time delay of the connection
\item \textbf{knowndbs} is a file containing the list of available databases
\item \textbf{dbplaces} is a file containing the path of the available databases
\end{itemize}



You may want to change the port of the socket server, according to the availabilities and restricttions on your machine.
For example , lets use the port 49152 in a new racnucd.new file.

<<modifyinit,fig=F,eval=T>>=
initline <- readLines("./ACNUC_HOME/ACNUC_SOFT/racnucd/racnucd.ini")
initline[1]="port=49152"
writeLines(initline, "./ACNUC_HOME/ACNUC_SOFT/racnucd/racnucd.new")
cat(readLines("./ACNUC_HOME/ACNUC_SOFT/racnucd/racnucd.new"), sep = "\n")
@ 

 
\subsubsection{Configuring the knowndbs file.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The \textbf{knowndbs} contains:

<<showmeknowdbs,fig=F,eval=T>>=
cat(readLines("./ACNUC_HOME/ACNUC_SOFT/racnucd/knowndbs"),sep = "\n")
@ 

Each line defines a database,  the four fields indicating respectively the name
 of the database, its status  (\textit{on} or \textit{off}), a tag and a short description.
 
You should set the files \textbf{knowndbs}  according to your installation.
Let's call the database you installed previously \textit{demoacnuc}.
Modify  the \textbf{knowndbs} as follows:
\begin{verbatim}
demoacnuc | on |    | Demo Database | 
\end{verbatim}

<<modifyknowndbs,fig=F,eval=T>>=
writeLines("demoacnuc | on |    | Demo Database | ", "./ACNUC_HOME/ACNUC_SOFT/racnucd/knowndbs")
knowndbs <- readLines("./ACNUC_HOME/ACNUC_SOFT/racnucd/knowndbs")
cat(knowndbs, sep = "\n")
@ 

\subsubsection{Configuring the dbplaces file.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


The \textbf{dbplaces} contains:

<<showmedbplaces,fig=F,eval=T>>=
dbplaces <- readLines("./ACNUC_HOME/ACNUC_SOFT/racnucd/dbplaces")
cat(dbplaces, sep = "\n")
@

Each line set the acnuc and gcgacnuc variables for each   database.


You should set the files \textbf{dbplaces}  according to your installation:
 modify  the \textbf{dbplaces} as follows:
\begin{verbatim}
setenv  demoacnuc       'ACNUC_HOME/ACNUC_DB/demoacnuc/index ACNUC_HOME/ACNUC_DB/demoacnuc/flat_files'
\end{verbatim}

<<modifydbplaces,fig=F,eval=T>>=
indexpath <- normalizePath("./ACNUC_HOME/ACNUC_DB/demoacnuc/index")
ffpath <- normalizePath("./ACNUC_HOME/ACNUC_DB/demoacnuc/flat_files")
newdb <- paste("setenv demoacnuc '", indexpath, " ", ffpath, "'", sep = "", collapse = "")
writeLines(newdb, "./ACNUC_HOME/ACNUC_SOFT/racnucd/dbplaces")
dbplaces <- readLines("./ACNUC_HOME/ACNUC_SOFT/racnucd/dbplaces")
cat(dbplaces, sep = "\n")
@

\subsubsection{Launch the server.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


Finaly, in the ACNUC\_HOME/ACNUC\_SOFT/racnucd/ directory, lauche the server as follow :

<<startserver,fig=F,eval=T>>=
setwd("./ACNUC_HOME/ACNUC_SOFT/racnucd")
system("./racnucd racnucd.new > racnucd.log &")
Sys.sleep(1)
system("ps | grep racnucd", intern = TRUE)
cat(readLines("racnucd.log"), sep = "\n")
setwd(pwd)
@ 

The server is now ready.

\subsection{Using seqinR to query your local socket server.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Launch \Rlogo{}, load the \texttt{seqinr} package  and type


\begin{verbatim}
choosebank(host="my_machine",port=49152,info=T)
\end{verbatim}

for example:


<<trylocalserver,fig=F,eval=T>>=
library(seqinr)
#system("hostname", intern = TRUE) -> hostname
hostname <- "localhost"
choosebank(host = hostname,port=49152, info = TRUE)
@ 


You can query the database. For example:

<<tryquery,fig=F,eval=T>>=
choosebank(bank = "demoacnuc",host = hostname,port=49152)
query("mylist", "k=rib@ prot@")
mylist$nelem
getName(mylist$req)
@ 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Building your own  ACNUC database.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

One of the interest of a local server is to be able use your own ACNUC
database.


\subsection{Database flatfiles formats.}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ACNUC database are build from flat files in several possible format : EMBL, Genbank or
SwissProt. Instructions to install ACNUC databases are given at this url :
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/localinstall.html
\end{verbatim}


\subsection{Download the ACNUC dababase management tools.}
 
 
 
 
 The code source of the ACNUC tools server are available on the PBIL server  at this url:
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/acnucsoft.tar
\end{verbatim}

\subsection{Install the ACNUC dababase management tools.}
ANCUC management tools are described at this url :
\begin{verbatim}
http://pbil.univ-lyon1.fr/databases/acnuc/acnuc_gestion.html
\end{verbatim}

Let ACNUC\_HOME/ACNUC\_SOFT/tools be the base directory for the ACNUC tools.


<<make ACNUC_SOFT,fig=F,eval=T>>=
dir.create("./ACNUC_HOME/ACNUC_SOFT/tools", showWarning = FALSE)
@

\begin{itemize}
\item Dowload the \texttt{acnucsoft.tar} file into ACNUC\_HOME/ACNUC\_SOFT/tools.

% Mettre eval=F apres premier download
<<dowloadacnucsoft,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/acnuc/unix/acnucsoft.tar",
destfile = "./ACNUC_HOME/ACNUC_SOFT/tools/acnucsoft.tar")
@


\item Untar the \texttt{acnucsoft.tar} file 

<<decompressacnucsoft,fig=F,eval=T>>=
setwd("./ACNUC_HOME/ACNUC_SOFT/tools/")
system("tar -xvf acnucsoft.tar")
system("rm -f acnucsoft.tar")
setwd(pwd)
@ 




\item Go into ACNUC\_SOFT/ and type;
\begin{verbatim}
make
\end{verbatim}
This should create the ACNUC management tools and ACNUC querying tools.

<<makeacucsoft,fig=F,eval=T>>=
setwd("./ACNUC_HOME/ACNUC_SOFT/tools/")
system("make")
dir()
setwd(pwd)
@ 

\end{itemize}
 
\subsection{Database building : index generation}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


You can now build your own database.
All you need is a flat files
in EMBL, GenBank or SwissProt format. You can download a file example at :
\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/escherichia_uniprot.dat.Z
\end{verbatim}

Let's use this SwissProt file to build your database
\begin{itemize}

\item Let ACNUC\_HOME/ACNUC\_DB/mydb be the directory for your databases.


<<make ACNUC_MYDB,fig=F,eval=T>>=
dir.create("./ACNUC_HOME/ACNUC_DB/mydb", showWarning = FALSE)
@
This directory should contain the  \textit{index} and \textit{flat\_files} directories.

<<make ACNUC_MYDB_sousdir,fig=F,eval=T>>=
dir.create("./ACNUC_HOME/ACNUC_DB/mydb/index", showWarning = FALSE)
dir.create("./ACNUC_HOME/ACNUC_DB/mydb/flat_files", showWarning = FALSE)
@

\item Download the \texttt{escherichia\_uniprot.dat.Z} file into ACNUC\_HOME/ACNUC\_DB/mydb/flat\_files.

% Mettre eval=F apres premier download
<<dowloadacnucflat,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/escherichia_uniprot.dat.Z",
destfile = "./ACNUC_HOME/ACNUC_DB/mydb/flat_files/escherichia_uniprot.dat.Z")
@


\item Uncompress the \texttt{escherichia\_uniprot.dat.Z} file 

<<decompressacnucflat,fig=F,eval=T>>=
setwd("./ACNUC_HOME/ACNUC_DB/mydb/flat_files/")
system("gunzip -f escherichia_uniprot.dat.Z")
setwd(pwd)
@ 


\item A simple building of the index can be done with the script  \texttt{buildindex.csh} available at:

\begin{verbatim}
ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/buildindex.csh
\end{verbatim}


You can copy this file in ACNUC\_HOME/ACNUC\_DB/mydb and execute it by typing::

\begin{verbatim}
./buildindex.csh escherichia_uniprot
\end{verbatim}

% Mettre eval=F apres premier download
<<dowloadacnucscript,fig=F,eval=T>>=
download.file("ftp://pbil.univ-lyon1.fr/pub/seqinr/demoacnuc/buildindex.csh",
destfile = "./ACNUC_HOME/ACNUC_DB/mydb/buildindex.csh")
setwd("./ACNUC_HOME/ACNUC_DB/mydb/")
system("chmod +x ./buildindex.csh")
system("./buildindex.csh escherichia_uniprot >  ./build.log")
cat(readLines("build.log",50), sep = "\n")
cat(tail(readLines("build.log"),50), sep = "\n")
setwd(pwd)
@
You can check the building in the \texttt{build.log} file.

\end{itemize}




%%%%%%%%%%%%%%
\section{Misc} 
%%%%%%%%%%%%%

\subsection{Other tools for acnuc}

Several powerful tools dedicated to query ACNUC databases are available. 
The programs \textbf{query} and \textbf{query\_win} allow to query an ACNUC database according to the same
criteria than described  in \seqinr{}. It allows as well several functionality to extract biological data.
\textbf{query\_win} is a graphical version of query (\textit{cf} figure \ref{queryw}).
\textbf{query} is an command-line version which allows to query and ACNUC database through scripts.
Both \textbf{query} and  \textbf{query\_win} are available as a
\textit{client} or a \textit{local} application. More information on these programs can be found at:
\url{http://pbil.univ-lyon1.fr/software/query_win.html}

\begin{figure}
\fbox{
\begin{minipage}{\textwidth}
\includegraphics[width=\textwidth]{../figs/query_win_screenshot}
\caption{Screenshot of query\_win}
\label{queryw}
\end{minipage}
}
\end{figure}


Note:
The \textit{local} version of \textbf{query} is distributed with the ACNUC management  tools,
 thus it is already available in your ./ACNUC\_HOME/ACNUC\_SOFT/tools/ directory.
Before using it you need to set two environment  variables, \textit{acnuc} and \textit{gcganuc} :
\begin{verbatim}
setenv acnuc MYDATABASE/index
setenv gcgacnuc MYDATABASE/flat_files 
\end{verbatim}

where MYDATABASE is the path to the database you want to query ( for example: ./ACNUC\_HOME/ACNUC\_DB/demoacnuc/
 or ./ACNUC\_HOME/ACNUC\_DB/mydb/)
  
 




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Technical description of the racnucd daemon}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Technical information about the acnuc socket server is available at this url:
\url{http://pbil.univ-lyon1.fr/databases/acnuc/racnucd.html}.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{ACNUC remote access protocol}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Description of the socket communication protocol with acnuc is availble at this url:
\url{http://pbil.univ-lyon1.fr/databases/acnuc/remote_acnuc.html}




\section{Citation} 
%%%%%%%%%%%%%

You can use a citation along these lines:

\vspace{0.2cm}

\noindent\fbox{\begin{minipage}{\textwidth}
\noindent Sequences from [\textit{cite your source of data}] were structured under the 
ACNUC model \cite{acnuc1985}, hosted [at \textit{give your URL if
public}] by an ACNUC server \cite{acnuc2007} and analyzed with 
the \seqinr{} client \cite{seqinr} under the \Rlogo{} statistical environment \cite{RfromR}.
\end{minipage}}

\vspace{0.2cm}

For \LaTeX{} users, these references are available in the \texttt{book.bib} file that ships
with \seqinr{} in the \texttt{seqinr/doc/src/config/} folder. To locate this file on your
computer try:

<<showbookbib,fig=F>>=
(seqinrloc <- normalizePath(.path.package("seqinr")))
setwd(seqinrloc)
dir()
setwd("./doc/src/config")
dir()
cat(readLines("book.bib", n = 5), sep = "\n")
@ 

%
% For Sweave users, go back home:
%
<<gobackhome,fig=F,echo=F,results=hide>>=
setwd(pwd)
@ 

\SweaveInput{../config/sessionInfo.rnw}

% END - DO NOT REMOVE THIS LINE

%%%%%%%%%%%%  BIBLIOGRAPHY %%%%%%%%%%%%%%%%%
\clearpage
\addcontentsline{toc}{section}{References}
\bibliographystyle{plain}
\bibliography{../config/book}
\end{document}
