\documentclass{article}
\input{../config/commontex}

\title{Informations about databases available at pbil}
\author{Lobry, J.R.}

\usepackage{Sweave}
\begin{document}
%
% To change the R input/output style:
%
\definecolor{Soutput}{rgb}{0,0,0.56}
\definecolor{Sinput}{rgb}{0.56,0,0}
\DefineVerbatimEnvironment{Sinput}{Verbatim}
{formatcom={\color{Sinput}},fontsize=\footnotesize, baselinestretch=0.75}
\DefineVerbatimEnvironment{Soutput}{Verbatim}
{formatcom={\color{Soutput}},fontsize=\footnotesize, baselinestretch=0.75}
%
% This removes the extra spacing after code and output chunks in Sweave,
% but keeps the spacing around the whole block.
%
\fvset{listparameters={\setlength{\topsep}{0pt}}}
\renewenvironment{Schunk}{\vspace{\topsep}}{\vspace{\topsep}}
%
% Rlogo
%
\newcommand{\Rlogo}{\protect\includegraphics[height=1.8ex,keepaspectratio]{../figs/Rlogo.pdf}}
%
% Shortcut for seqinR:
%
\newcommand{\seqinr}{\texttt{seqin\bf{R}}}
\newcommand{\Seqinr}{\texttt{Seqin\bf{R}}}
\fvset{fontsize= \scriptsize}
%
% R output options and libraries to be loaded.
%
%
%  Sweave Options
%
% Put all figures in the fig folder and start the name with current file name.
% Do not produce EPS files
%


\maketitle
% BEGIN - DO NOT REMOVE THIS LINE
\label{subsequence}

\section{Introduction}
This section was compiled on \today. The list of available database at pbil 
(\url{http://pbil.univ-lyon1.fr/}) was:

\begin{Schunk}
\begin{Sinput}
 bankDefault <- choosebank()
 bankTP <- choosebank(tagbank = "TP")
 bankDEV <- choosebank(tagbank = "DEV")
 (banknames <- c(bankDefault, bankTP, bankDEV))
\end{Sinput}
\begin{Soutput}
 [1] "genbank"      "embl"         "emblwgs"      "swissprot"   
 [5] "ensembl"      "refseq"       "nrsub"        "hobacnucl"   
 [9] "hobacprot"    "hovergendna"  "hovergen"     "hogenom"     
[13] "hogenomdna"   "hogennucl"    "hogenprot"    "hoverclnu"   
[17] "hoverclpr"    "homolens3"    "homolens3dna" "homolens"    
[21] "homolensdna"  "greview"      "polymorphix"  "emglib"      
[25] "HAMAPnucl"    "HAMAPprot"    "taxobacgen"   "apis"        
[29] "human"        "emblTP"       "swissprotTP"  "hoverprotTP" 
[33] "hovernuclTP"  "trypano"      "ensembl24"    "ensembl34"   
[37] "ensembl41"    "ensembl47"    "ensembl49"    "macaca45"    
[41] "dog45"        "dog47"        "equus49"      "pongo49"     
[45] "rattus49"     "mouse38"      "homolens4"    "homolens4dna"
[49] "hoppsigen"    "nurebnucl"    "nurebprot"    "hogendnucl"  
[53] "hogendprot"   "genomicro1"   "genomicro2"   "genomicro3"  
[57] "genomicro4"   "dickeya"      "tetra53"      "trypanosoma" 
\end{Soutput}
\end{Schunk}

This \LaTeX~file was automatically generated by the following \Rlogo{}~code:

\begin{Schunk}
\begin{Sinput}
 for (b in banknames) {
     cat(paste("\\section{", b, "}"), sep = "\n")
     openTry <- try(choosebank(b))
     if (inherits(openTry, "try-error")) {
         cat("There was a problem while trying to open this bank.\n")
         next
     }
     bankdetails <- sapply(banknameSocket$details, stresc, 
         USE.NAMES = FALSE)
     cat("\\textbf{Bank details}", sep = "\n")
     cat(bankdetails, sep = "\\\\\n")
     cat("\n")
     cat("\\textbf{Type names}", sep = "\n")
     types <- getType()
     if (is.null(nrow(types))) {
         cat("There are no subsequence type in this database", 
             sep = "\n")
     }
     else {
         cat("\\noindent\\begin{tabular}{llr}", sep = "\n")
         cat("\\hline \\hline", sep = "\n")
         cat("name & description & count \\\\", sep = "\n")
         cat("\\hline", sep = "\n")
         sumnelem <- 0
         for (i in 1:nrow(types)) {
             querytry <- try(query("mylist", paste("T=", types[i, 
                 "sname"]), virtual = TRUE))
             if (inherits(querytry, "try-error")) {
                 nelem <- 0
             }
             else {
                 nelem <- mylist$nelem
             }
             sumnelem <- sumnelem + nelem
             cat(paste(stresc(types[i, "sname"]), " & ", stresc(types[i, 
                 "libel"]), " & ", formatC(nelem, big.mark = ",", 
                 format = "d"), "\\\\"), sep = "\n")
         }
         cat("\\hline", sep = "\n")
         cat(paste(" & Total: &", formatC(sumnelem, big.mark = ",", 
             format = "d"), "\\\\"), sep = "\n")
         cat("\\hline \\hline", sep = "\n")
         cat("\\end{tabular}", sep = "\n")
         cat("\n")
     }
     closebank()
 }
\end{Sinput}
\section{ genbank }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
          GenBank Rel. 171 (15 April 2009) Last Updated: Apr 23, 2009\\
103,287,086,629 bases; 103,570,547 sequences; 6,354,023 subseqs; 549,786 refers.\\
Software by M. Gouy, Lab. Biometrie et Biologie Evolutive, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  6,900,945 \\
LOCUS  &  sequenced DNA fragment  &  100,225,982 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  643,091 \\
RRNA  &  .RR mature ribosomal RNA  &  1,722,748 \\
SCRNA  &  .SC small cytoplasmic RNA  &  146 \\
SNRNA  &  .SN small nuclear RNA  &  418 \\
TMRNA  &  .TM transfer messenger RNA  &  364 \\
TRNA  &  .TR mature transfer RNA  &  430,876 \\
\hline
 & Total: & 109,924,570 \\
\hline \hline
\end{tabular}

\section{ embl }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
        EMBL Library Release 99 (March 2009) Last Updated: Apr 23, 2009\\
128,033,198,490 bases; 106,636,474 sequences; 13,957,419 subseqs; 538,628 refers.\\
Software by M. Gouy, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  14,501,284 \\
ID  &  Locus entry  &  103,200,038 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  641,350 \\
NCRNA  &  .NC non protein-coding RNA  &  70,447 \\
RRNA  &  .RR Ribosomal RNA coding gene  &  1,725,176 \\
SCRNA  &  .SC small cytoplasmic RNA  &  0 \\
SNRNA  &  .SN small nuclear RNA  &  0 \\
TMRNA  &  .TM transfer messenger RNA  &  206 \\
TRNA  &  .TR Transfer RNA coding gene  &  455,392 \\
\hline
 & Total: & 120,593,893 \\
\hline \hline
\end{tabular}

\section{ emblwgs }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
        EMBL Whole Genome Shotgun sequences Release 99  (March 2009)  \\
143,979,753,892 bases; 49,058,862 sequences; 1,634,710 subseqs; 637 refers.\\
Retrieval software by M. Gouy, Biometrie et Biologie Evolutive, Univ Lyon I. 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  1,606,862 \\
ID  &  EMBL sequence data library entry  &  49,058,182 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  1,323 \\
RRNA  &  .RR ribosomal RNA coding region  &  3,742 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  23,463 \\
\hline
 & Total: & 50,693,572 \\
\hline \hline
\end{tabular}

\section{ swissprot }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                       \\
    UniProt Rel. 15 (SWISS-PROT 57 + TrEMBL 40): Last Updated: Apr 21, 2009\\
          2,619,864,771 amino acids; 7,990,560 sequences; 309,067 references.\\
          Non-redundant compilation of SWISS-PROT + TrEMBL\\
Software by M. Gouy \& L. Duret, Laboratoire de biometrie, Universite Lyon I.

\textbf{Type names}
There are no subsequence type in this database
\section{ ensembl }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****\\
             Ensembl Release 49	     		 Last Updated: Apr 23, 2008\\
90,338,630,754 bases; 3,499,715 sequences; 9,289,073 subseqs; 0 refers.\\
\\
 Aedes aegypti - Release 49\_1b \\
 Anopheles gambiae - Release 49\_3j \\
 Apis mellifera - Release 38\_2d \\
 Bos taurus - Release 49\_3f \\
 Caenorhabditis elegans - Release 49\_180a \\
 Canis familiaris - Release 49\_2g \\
 Cavia porcellus - Release 49\_1c \\
 Ciona intestinalis - Release 49\_2i \\
 Ciona savignyi - Release 49\_2f \\
 Danio rerio - Release 49\_7c \\
 Dasypus novemcinctus - Release 49\_1f \\
 Drosophila melanogaster - Release 49\_44 \\
 Echinops telfairi - Release 49\_1e \\
 Equus caballus - Release 49\_2 \\
 Erinaceus europaeus - Release 49\_1c \\
 Felis catus - Release 49\_1c \\
 Gallus gallus - Release 49\_2g \\
 Gasterosteus aculeatus - Release 49\_1f \\
 Homo sapiens - Release 49\_36k \\
 Loxodonta africana - Release 49\_1d \\
 Macaca mulatta - Release 49\_10h \\
 Microcebus murinus - Release 49\_1 \\
 Monodelphis domestica - Release 49\_5d \\
 Mus musculus - Release 49\_37b \\
 Myotis lucifugus - Release 49\_1e \\
 Ochotona princeps - Release 49\_1 \\
 Ornithorhynchus anatinus - Release 49\_1f \\
 Oryctolagus cuniculus - Release 49\_1f \\
 Oryzias latipes - Release 49\_1e \\
 Otolemur garnettii - Release 49\_1e \\
 Pan troglodytes - Release 49\_21h \\
 Pongo pygmaeus - Release 49\_1 \\
 Rattus norvegicus - Release 49\_34s \\
 Saccharomyces cerevisiae - Release 49\_1h \\
 Sorex araneus - Release 49\_1c \\
 Spermophilus tridecemlineatus - Release 49\_1e \\
 Takifugu rubripes - Release 49\_4i \\
 Tetraodon nigroviridis - Release 49\_1k \\
 Tupaia belangeri - Release 49\_1d \\
 Xenopus tropicalis - Release 49\_41i \\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  307,441 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  800,830 \\
CDS  &  .PE protein coding region  &  892,572 \\
GENE  &  .GN gene  &  805,489 \\
ID  &  EMBL sequence data library entry  &  3,499,715 \\
INT\_INT  &  .IN  internal intron  &  7,157,683 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  130,547 \\
MRNA  &  .MR mRNA  &  892,572 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 14,486,849 \\
\hline \hline
\end{tabular}

\section{ refseq }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****    \\
    RNA sequences - Release 33 (January 16, 2009) Last Updated: Feb 13, 2009\\
2,746,151,813 bases; 1,685,610 sequences; 522,605 subseqs; 142,084 refers.\\
 		NCBI Reference Sequence (RefSeq) Database\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  0 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  0 \\
CDS  &  .PE protein coding region  &  1,641,694 \\
INT\_INT  &  .IN  internal intron  &  0 \\
LOCUS  &  sequenced DNA fragment  &  564,617 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  0 \\
RRNA  &  .RR ribosomal RNA coding region  &  1,904 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 2,208,215 \\
\hline \hline
\end{tabular}

\section{ nrsub }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****\\
               NRSub database release 10.1 (December 1997)\\
                    Bacillus subtilis complete genome\\
             Sequence data taken from the SubtiList database\\
     Institut Pasteur - Unite de Regulation de l'Expression Genetique\\
                Extra annotations provided by G. Perriere\\
           Laboratoire BGBP - Universite Claude Bernard, Lyon 1

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  4,100 \\
ID  &  EMBL sequence data library entry  &  1 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  0 \\
RRNA  &  .RR ribosomal RNA coding region  &  30 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  2 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  88 \\
\hline
 & Total: & 4,221 \\
\hline \hline
\end{tabular}

\section{ hobacnucl }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
          HOBACGEN - genomic data - Release 10 (February 12 2002)\\
432,023,804 bases; 168,814 sequences; 293,669 subseqs; 52,735 references.\\
                                                                               \\
              Bacteria + Archaea + Saccharomyces cerevisiae\\
            Genomic data from EMBL Release 69 (December 2001)\\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  306,455 \\
ID  &  EMBL sequence data library entry  &  94,694 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  2,299 \\
RRNA  &  .RR ribosomal RNA coding region  &  51,562 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  41 \\
SNRNA  &  .SN small nuclear RNA coding region  &  193 \\
TRNA  &  .TR transfer RNA coding region  &  7,239 \\
\hline
 & Total: & 462,483 \\
\hline \hline
\end{tabular}

\section{ hobacprot }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****\\
           HOBACGEN - protein data - Release 10 (February 12 2002)\\
          79,755,852 amino acids; 260,025 sequences; 37,383 references.\\
               \\
              Bacteria + Archaea + Saccharomyces cerevisiae\\
   Protein data from SWISS-PROT 40 + TrEMBL 19 + TrEMBL\_NEW: January 25, 2002\\
\\
Software: M. Gouy \& M. Jacobzone\\
Data maintenance: L. Duret \& G. Perriere\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ hovergendna }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
 HOVERGEN - genomic data - Release 48 (May 24 2007) Last Updated: May 24, 2007\\
2,500,248,516 bases; 541,405 sequences; 1,005,089 subseqs; 117,556 refers.\\
                                                                               \\
                       Vertebrate (chordata)\\
    Genomic data from EMBL Library Release 90 (March 2007)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  129,921 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  120,642 \\
CDS  &  .PE protein coding region  &  613,473 \\
ID  &  EMBL sequence data library entry  &  371,759 \\
INT\_INT  &  .IN  internal intron  &  172,068 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  249 \\
RRNA  &  .RR ribosomal RNA coding region  &  9,873 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  24 \\
SNRNA  &  .SN small nuclear RNA coding region  &  55 \\
TRNA  &  .TR transfer RNA coding region  &  128,430 \\
\hline
 & Total: & 1,546,494 \\
\hline \hline
\end{tabular}

\section{ hovergen }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                       \\
 HOVERGEN - protein data - Release 48 (May 24 2007) Last Updated: May 24, 2007\\
          142,891,140 amino acids; 415,383 sequences; 114,560 references.\\
\\
                       Vertebrate (chordata)	  \\
    Protein data from UniProt Rel. 10 (SWISS-PROT 52 + TrEMBL 35) May 2007\\
\\
Software: M. Gouy \& M. Jacobzone\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ hogenom }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
 HOGENOM - protein data - Release 04 (Sept 18,2007) Last Updated: Feb 27, 2008\\
          755,031,736 amino acids; 2,142,639 sequences; 0 references.\\
                                                                               \\
                        Fully Sequenced Organisms\\
   				Protein data \\
	  511 fully sequenced organisms (eukarya, bacteria, archaea)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ hogenomdna }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
 HOGENOM - genomic data - Release 04 (Sept 18,2007) Last Updated: Feb 21, 2008\\
14,692,834,718 bases; 134,844 sequences; 7,862,206 subseqs; 512 refers.\\
                                                                               \\
                        Fully Sequenced Organisms\\
   				Genomes \\
	  511 fully sequenced organisms (eukarya, bacteria, archaea)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  1,476,296 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  1,720,484 \\
CDS  &  .PE protein coding region  &  2,125,031 \\
ID  &  EMBL sequence data library entry  &  54,323 \\
INT\_INT  &  .IN  internal intron  &  2,560,918 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  22,520 \\
RRNA  &  .RR ribosomal RNA coding region  &  6,378 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  11 \\
SNRNA  &  .SN small nuclear RNA coding region  &  231 \\
TRNA  &  .TR transfer RNA coding region  &  30,858 \\
\hline
 & Total: & 7,997,050 \\
\hline \hline
\end{tabular}

\section{ hogennucl }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
  HOGENOM - genomic data - Release 03 (Oct 14 2005) Last Updated: Nov  7, 2005\\
2,538,433,251 bases; 227,950 sequences; 3,166,480 subseqs; 82,283 refers.\\
                                                                               \\
                        Fully Sequenced Organisms\\
   Protein data from http://www.ebi.ac.uk/proteome/ (August, 2005)\\
          Genomic data from GenomeReview  (June 2005) \\
                  and  EMBL (June 2005)\\
	   ( 263 fully sequenced organisms)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  340 \\
3'NCR  &  .3F  3'-non coding region  &  852,742 \\
5'INT  &  .5I 5'intron  &  1,445 \\
5'NCR  &  .5F  5'-non coding region  &  873,248 \\
CDS  &  .PE protein coding region  &  1,064,998 \\
ID  &  EMBL sequence data library entry  &  204,502 \\
INT\_INT  &  .IN  internal intron  &  646,105 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  860 \\
RRNA  &  .RR ribosomal RNA coding region  &  5,819 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  29 \\
SNRNA  &  .SN small nuclear RNA coding region  &  459 \\
TRNA  &  .TR transfer RNA coding region  &  49,239 \\
\hline
 & Total: & 3,699,786 \\
\hline \hline
\end{tabular}

\section{ hogenprot }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
  HOGENOM - protein data - Release 03 (Oct 14 2005) Last Updated: Mar 10, 2006\\
          339,891,443 amino acids; 950,216 sequences; 92,805 references.\\
                                                                               \\
                        Fully Sequenced Organisms\\
   Protein data from http://www.ebi.ac.uk/proteome/ (August 2005)\\
	            ( 263 fully sequenced organisms)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ hoverclnu }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
         HOVERGEN CLEAN - genomic data - Release 46 (Jun 10 2004)\\
894,369,756 bases; 312,987 sequences; 796,415 subseqs; 99,342 refers.\\
                                                                               \\
                       Vertebrate (chordata)\\
             Genomic data from EMBL Release 78  (March 2004)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  514 \\
3'NCR  &  .3F  3'-non coding region  &  178,356 \\
5'INT  &  .5I 5'intron  &  1,377 \\
5'NCR  &  .5F  5'-non coding region  &  166,924 \\
CDS  &  .PE protein coding region  &  289,107 \\
ID  &  EMBL sequence data library entry  &  218,165 \\
INT\_INT  &  .IN  internal intron  &  133,109 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  169 \\
RRNA  &  .RR ribosomal RNA coding region  &  3,064 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  15 \\
SNRNA  &  .SN small nuclear RNA coding region  &  50 \\
TRNA  &  .TR transfer RNA coding region  &  43,253 \\
\hline
 & Total: & 1,034,103 \\
\hline \hline
\end{tabular}

\section{ hoverclpr }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                       \\
          HOVERGEN CLEAN - protein data - Release 46 (Jun 10 2004)\\
          75,885,664 amino acids; 219,552 sequences; 89,885 references.\\
\\
                       Vertebrate (chordata)	  \\
Protein data from SWISS-PROT Rel. 43  + TrEMBL Rel. 26 + TrEMBL\_NEW: May 17, 2004\\
\\
Software: M. Gouy \& M. Jacobzone\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ homolens3 }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
      HOMOLENS 3 - Homologous genes from Ensembl Last Updated: Jan 19, 2007\\
          224,528,520 amino acids; 474,339 sequences; 0 references.\\
	 \\
                        Ensembl 41 Organisms Translated CDS\\
Aedes aegypti                           41\_1a 11360/0/2/0 (0\%/0\%/0\%)\\
Anopheles gambiae                       41\_3d 13510/0/31/0 (0\%/0\%/0\%)\\
Apis mellifera                          38\_2d 27755/1/269/0 (0\%/0\%/0\%)\\
Bos taurus                              41\_2 32556/7/620/12 (0\%/1\%/0\%)\\
Caenorhabditis elegans                  41\_160 25218/1/0/0 (0\%/0\%/0\%)\\
Canis familiaris                        41\_1j 29813/0/0/0 (0\%/0\%/0\%)\\
Caenorhabditis briggsae                 25 14712/0/23/1 (0\%/0\%/0\%)\\
Ciona intestinalis                      41\_2c 20000/0/128/0 (0\%/0\%/0\%)\\
Ciona savignyi                          41\_2b 20150/1/27/0 (0\%/0\%/0\%)\\
Danio rerio                             41\_6b 36065/5/361/0 (0\%/1\%/0\%)\\
Dasypus novemcinctus                    40\_1 13567/12/8857/0 (0\%/65\%/0\%)\\
Drosophila melanogaster                 41\_43 19577/33/1/0 (0\%/0\%/0\%)\\
Echinops telfairi                       40\_1 14309/8/9348/0 (0\%/65\%/0\%)\\
Gallus gallus                           41\_1p 20667/13/455/0 (0\%/2\%/0\%)\\
Gasterosteus aculeatus                  41\_1a 27181/13/138/0 (0\%/0\%/0\%)\\
Homo sapiens                            41\_36c 47004/41/6/0 (0\%/0\%/0\%)\\
Loxodonta africana                      40\_1 14366/10/9618/0 (0\%/66\%/0\%)\\
Macaca mulatta                          41\_10a 36446/14/491/0 (0\%/1\%/0\%)\\
Monodelphis domestica                   41\_3a 30358/0/80/0 (0\%/0\%/0\%)\\
Mus musculus                            41\_36b 29026/34/2/0 (0\%/0\%/0\%)\\
Oryctolagus cuniculus                   41\_1a 13705/4/8615/0 (0\%/62\%/0\%)\\
Oryzias latipes                         41\_1 25880/0/546/0 (0\%/2\%/0\%)\\
Pan troglodytes                         41\_21 32667/4/739/0 (0\%/2\%/0\%)\\
Rattus norvegicus                       41\_34k 32996/34/686/0 (0\%/2\%/0\%)\\
Saccharomyces cerevisiae                41\_1d 4767/2/0/0 (0\%/0\%/0\%)\\
Takifugu rubripes                       41\_4c 22102/0/283/0 (0\%/1\%/0\%)\\
Tetraodon nigroviridis                  41\_1g 15841/1/225/0 (0\%/1\%/0\%)\\
Xenopus tropicalis                      41\_41b 28324/0/626/0 (0\%/2\%/0\%)\\
 \\
	     \\
Software: M. Gouy \& M. Jacobzone\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ homolens3dna }
\textbf{Bank details}
            ****     ACNUC Data Base Content      ****  \\
       HOMOLENS 3 Homologous genes from Ensembl 41 Last Updated: Jan 19, 2007\\
32,635,729,329 bases; 81,903 sequences; 5,717,782 subseqs; 0 refers.\\
\\
Aedes aegypti                           41\_1a 11360/0/2/0 (0\%/0\%/0\%)\\
Anopheles gambiae                       41\_3d 13510/0/31/0 (0\%/0\%/0\%)\\
Apis mellifera                          38\_2d 27755/1/269/0 (0\%/0\%/0\%)\\
Bos taurus                              41\_2 32556/7/620/12 (0\%/1\%/0\%)\\
Caenorhabditis elegans                  41\_160 25218/1/0/0 (0\%/0\%/0\%)\\
Canis familiaris                        41\_1j 29813/0/0/0 (0\%/0\%/0\%)\\
Caenorhabditis briggsae                 25 14712/0/23/1 (0\%/0\%/0\%)\\
Ciona intestinalis                      41\_2c 20000/0/128/0 (0\%/0\%/0\%)\\
Ciona savignyi                          41\_2b 20150/1/27/0 (0\%/0\%/0\%)\\
Danio rerio                             41\_6b 36065/5/361/0 (0\%/1\%/0\%)\\
Dasypus novemcinctus                    40\_1 13567/12/8857/0 (0\%/65\%/0\%)\\
Drosophila melanogaster                 41\_43 19577/33/1/0 (0\%/0\%/0\%)\\
Echinops telfairi                       40\_1 14309/8/9348/0 (0\%/65\%/0\%)\\
Gallus gallus                           41\_1p 20667/13/455/0 (0\%/2\%/0\%)\\
Gasterosteus aculeatus                  41\_1a 27181/13/138/0 (0\%/0\%/0\%)\\
Homo sapiens                            41\_36c 47004/41/6/0 (0\%/0\%/0\%)\\
Loxodonta africana                      40\_1 14366/10/9618/0 (0\%/66\%/0\%)\\
Macaca mulatta                          41\_10a 36446/14/491/0 (0\%/1\%/0\%)\\
Monodelphis domestica                   41\_3a 30358/0/80/0 (0\%/0\%/0\%)\\
Mus musculus                            41\_36b 29026/34/2/0 (0\%/0\%/0\%)\\
Oryctolagus cuniculus                   41\_1a 13705/4/8615/0 (0\%/62\%/0\%)\\
Oryzias latipes                         41\_1 25880/0/546/0 (0\%/2\%/0\%)\\
Pan troglodytes                         41\_21 32667/4/739/0 (0\%/2\%/0\%)\\
Rattus norvegicus                       41\_34k 32996/34/686/0 (0\%/2\%/0\%)\\
Saccharomyces cerevisiae                41\_1d 4767/2/0/0 (0\%/0\%/0\%)\\
Takifugu rubripes                       41\_4c 22102/0/283/0 (0\%/1\%/0\%)\\
Tetraodon nigroviridis                  41\_1g 15841/1/225/0 (0\%/1\%/0\%)\\
Xenopus tropicalis                      41\_41b 28324/0/626/0 (0\%/2\%/0\%)\\
\\
	     \\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  188,371 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  485,692 \\
CDS  &  .PE protein coding region  &  659,680 \\
ID  &  EMBL sequence data library entry  &  81,903 \\
INT\_INT  &  .IN  internal intron  &  4,339,670 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  44,369 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 5,799,685 \\
\hline \hline
\end{tabular}

\section{ homolens }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****\\
   HOMOLENS 4 - Homologous genes from Ensembl(49)	 Last Updated: Jul  4, 2008\\
247,930,199 bases; 529 sequences; 64,224 subseqs; 206 refers.\\
\\
 Aedes aegypti - Release 49\_1b \\
 Anopheles gambiae - Release 49\_3j \\
 Apis mellifera - Release 38\_2d \\
 Bos taurus - Release 49\_3f \\
 Caenorhabditis elegans - Release 49\_180a \\
 Canis familiaris - Release 49\_2g \\
 Cavia porcellus - Release 49\_1c \\
 Ciona intestinalis - Release 49\_2i \\
 Ciona savignyi - Release 49\_2f \\
 Danio rerio - Release 49\_7c \\
 Dasypus novemcinctus - Release 49\_1f \\
 Drosophila melanogaster - Release 49\_44 \\
 Echinops telfairi - Release 49\_1e \\
 Equus caballus - Release 49\_2 \\
 Erinaceus europaeus - Release 49\_1c \\
 Felis catus - Release 49\_1c \\
 Gallus gallus - Release 49\_2g \\
 Gasterosteus aculeatus - Release 49\_1f \\
 Homo sapiens - Release 49\_36k \\
 Loxodonta africana - Release 49\_1d \\
 Macaca mulatta - Release 49\_10h \\
 Microcebus murinus - Release 49\_1 \\
 Monodelphis domestica - Release 49\_5d \\
 Mus musculus - Release 49\_37b \\
 Myotis lucifugus - Release 49\_1e \\
 Ochotona princeps - Release 49\_1 \\
 Ornithorhynchus anatinus - Release 49\_1f \\
 Oryctolagus cuniculus - Release 49\_1f \\
 Oryzias latipes - Release 49\_1e \\
 Otolemur garnettii - Release 49\_1e \\
 Pan troglodytes - Release 49\_21h \\
 Pongo pygmaeus - Release 49\_1 \\
 Rattus norvegicus - Release 49\_34s \\
 Saccharomyces cerevisiae - Release 49\_1h \\
 Sorex araneus - Release 49\_1c \\
 Spermophilus tridecemlineatus - Release 49\_1e \\
 Takifugu rubripes - Release 49\_4i \\
 Tetraodon nigroviridis - Release 49\_1k \\
 Tupaia belangeri - Release 49\_1d \\
 Xenopus tropicalis - Release 49\_41i \\


\textbf{Type names}
There are no subsequence type in this database
\section{ homolensdna }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****\\
         HOMOLENS 4 - Homologous genes from Ensembl(49)	Last Updated: Jul  4, 2008\\
55,129,547,735 bases; 178,069 sequences; 9,247,193 subseqs; 0 refers.\\
\\
 Aedes aegypti - Release 49\_1b \\
 Anopheles gambiae - Release 49\_3j \\
 Apis mellifera - Release 38\_2d \\
 Bos taurus - Release 49\_3f \\
 Caenorhabditis elegans - Release 49\_180a \\
 Canis familiaris - Release 49\_2g \\
 Cavia porcellus - Release 49\_1c \\
 Ciona intestinalis - Release 49\_2i \\
 Ciona savignyi - Release 49\_2f \\
 Danio rerio - Release 49\_7c \\
 Dasypus novemcinctus - Release 49\_1f \\
 Drosophila melanogaster - Release 49\_44 \\
 Echinops telfairi - Release 49\_1e \\
 Equus caballus - Release 49\_2 \\
 Erinaceus europaeus - Release 49\_1c \\
 Felis catus - Release 49\_1c \\
 Gallus gallus - Release 49\_2g \\
 Gasterosteus aculeatus - Release 49\_1f \\
 Homo sapiens - Release 49\_36k \\
 Loxodonta africana - Release 49\_1d \\
 Macaca mulatta - Release 49\_10h \\
 Microcebus murinus - Release 49\_1 \\
 Monodelphis domestica - Release 49\_5d \\
 Mus musculus - Release 49\_37b \\
 Myotis lucifugus - Release 49\_1e \\
 Ochotona princeps - Release 49\_1 \\
 Ornithorhynchus anatinus - Release 49\_1f \\
 Oryctolagus cuniculus - Release 49\_1f \\
 Oryzias latipes - Release 49\_1e \\
 Otolemur garnettii - Release 49\_1e \\
 Pan troglodytes - Release 49\_21h \\
 Pongo pygmaeus - Release 49\_1 \\
 Rattus norvegicus - Release 49\_34s \\
 Saccharomyces cerevisiae - Release 49\_1h \\
 Sorex araneus - Release 49\_1c \\
 Spermophilus tridecemlineatus - Release 49\_1e \\
 Takifugu rubripes - Release 49\_4i \\
 Tetraodon nigroviridis - Release 49\_1k \\
 Tupaia belangeri - Release 49\_1d \\
 Xenopus tropicalis - Release 49\_41i \\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  307,441 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  800,830 \\
CDS  &  .PE protein coding region  &  892,572 \\
ID  &  EMBL sequence data library entry  &  178,069 \\
INT\_INT  &  .IN  internal intron  &  7,157,683 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  88,667 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 9,425,262 \\
\hline \hline
\end{tabular}

\section{ greview }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
        EBI Genome Reviews. Acnuc Release 2. Last Updated: June 19, 2005\\
719,075,744 bases; 385 sequences; 1,611,759 subseqs; 227 refers.\\
225 organisms\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  513,862 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  418,539 \\
CDS  &  .PE protein coding region  &  663,801 \\
ID  &  EMBL sequence data library entry  &  385 \\
INT\_INT  &  .IN  internal intron  &  160 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  0 \\
RRNA  &  .RR ribosomal RNA coding region  &  2,553 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  11 \\
SNRNA  &  .SN small nuclear RNA coding region  &  46 \\
TRNA  &  .TR transfer RNA coding region  &  12,787 \\
\hline
 & Total: & 1,612,144 \\
\hline \hline
\end{tabular}

\section{ polymorphix }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
                 POLYBASE - Release 1  (June 20, 2003)\\
326,666,616 bases; 261,669 sequences; 489,209 subseqs; 21,100 refers.\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  0 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  0 \\
CDS  &  .PE protein coding region  &  149,266 \\
ID  &  EMBL sequence data library entry  &  168,502 \\
INT\_INT  &  .IN  internal intron  &  0 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  37,077 \\
RRNA  &  .RR ribosomal RNA coding region  &  66,154 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  45 \\
TRNA  &  .TR transfer RNA coding region  &  44,158 \\
VARIATION  &  .VA allelic variant  &  285,676 \\
\hline
 & Total: & 750,878 \\
\hline \hline
\end{tabular}

\section{ emglib }
\textbf{Bank details}
               ****     ACNUC Database Content      ****\\
                  EMGLib Release 5 (December 9, 2003)\\
434,648,385 bases; 174 sequences; 413,521 subseqs; 169 refers.\\
           Data compiled from various sources by Guy Perriere

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  404,721 \\
LOCUS  &  sequenced DNA fragment  &  174 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  239 \\
RRNA  &  .RR ribosomal RNA coding region  &  1,409 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  8 \\
SNRNA  &  .SN small nuclear RNA coding region  &  6 \\
TRNA  &  .TR transfer RNA coding region  &  7,138 \\
\hline
 & Total: & 413,695 \\
\hline \hline
\end{tabular}

\section{ HAMAPnucl }
There was a problem while trying to open this bank.
\section{ HAMAPprot }
There was a problem while trying to open this bank.
\section{ taxobacgen }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****\\
                 TaxoBacGen Rel. 7 (September 2005)\\
1,151,149,763 bases; 254,335 sequences; 847,767 subseqs; 63,879 refers.\\
	Data compiled from GenBank by Gregory Devulder \\
        Laboratoire de Biometrie \& Biologie Evolutive, Univ Lyon I\\
------------------------------\\
This database is a taxonomic genomic database. \\
It results from an expertise crossing the data nomenclature database DSMZ\\
\[http://www.dsmz.de/species/bacteria.htm Deutsche Sammlung von\\
Mikroorganismen und Zellkulturen GmbH, Braunschweig, Germany\]\\
and GenBank. \\
- Only contains sequences described under species present in \\
Bacterial Nomenclature Up-to-date.\\
- Names of species and genus validly published according to the\\
Bacteriological Code (names with standing in nomenclature) is \\
added in field "DEFINITION".\\
- A keyword "type strain" is added in field "FEATURES/source/strain" in\\
GenBank format definition to easyly identify Type Strain.\\
Taxobacgen is a genomic database designed for studies based on a strict\\
respect of up-to-date nomenclature and taxonomy.

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  879,340 \\
LOCUS  &  sequenced DNA fragment  &  168,243 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  3,720 \\
RRNA  &  .RR ribosomal RNA coding region  &  34,965 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  36 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  15,798 \\
\hline
 & Total: & 1,102,102 \\
\hline \hline
\end{tabular}

\section{ apis }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
  Apis mellifera - based on Amel\_4.0 (March,2006) Last Updated: Feb 25, 2009\\
   217,194,876 bases; 16 sequences; 60,592 subseqs; 0 refers.\\
  Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
                 Data maintenance: L. Duret \& S. Penel\\
\\
          Laboratoire de Biometrie et Biologie Evolutive\\
         UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
       43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  6,545 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  6,543 \\
CDS  &  .PE protein coding region  &  6,704 \\
ID  &  EMBL sequence data library entry  &  16 \\
INT\_INT  &  .IN  internal intron  &  40,800 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  0 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 60,608 \\
\hline \hline
\end{tabular}

\section{ human }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
Homo sapiens - Release Ensembl Release 52 Databases. - (03/03/09) Last Updated: Mar  3, 2009\\
3,664,692,642 bases; 3,860 sequences; 676,152 subseqs; 0 refers.\\
MENU Nber of lines= 21                                                         

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  23,783 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  46,304 \\
CDS  &  .PE protein coding region  &  55,115 \\
ID  &  EMBL sequence data library entry  &  3,860 \\
INT\_INT  &  .IN  internal intron  &  476,982 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  18,853 \\
MRNA  &  .MR mRNA  &  55,115 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 680,012 \\
\hline \hline
\end{tabular}

\section{ emblTP }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
              EMBL Library Release 78 WITHOUT ESTs  (March 2004)\\
27,571,397,913 bases; 12,533,594 sequences; 1,604,500 subseqs; 339,186 refers.\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  1,746,728 \\
ID  &  Locus entry  &  11,856,048 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  109,101 \\
RRNA  &  .RR Ribosomal RNA coding gene  &  320,935 \\
SCRNA  &  .SC small cytoplasmic RNA  &  311 \\
SNRNA  &  .SN small nuclear RNA  &  1,687 \\
TRNA  &  .TR Transfer RNA coding gene  &  103,284 \\
\hline
 & Total: & 14,138,094 \\
\hline \hline
\end{tabular}

\section{ swissprotTP }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                       \\
  UniProt Rel. 1 (SWISS-PROT 43 + TrEMBL 26 + NEW): Last Updated: May  3, 2004\\
          459,974,342 amino acids; 1,451,384 sequences; 200,578 references.\\
          Non-redundant compilation of SWISS-PROT + TrEMBL (minus  data  \\
                     integrated  into  SWISS-PROT)\\
Software by M. Gouy \& L. Duret, Laboratoire de biometrie, Universite Lyon I.

\textbf{Type names}
There are no subsequence type in this database
\section{ hoverprotTP }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                       \\
         HOVERGEN - Release 45 (Jan 22 2004) Last Updated: Jan 22, 2004\\
          77,617,436 amino acids; 227,047 sequences; 85,918 references.\\
\\
                       Vertebrate (chordata)	  \\
Protein data from SWISS-PROT Rel. 42  + TrEMBL Rel. 25 + TrEMBL\_NEW: Dec 1, 2003\\
\\
Software: M. Gouy \& M. Jacobzone\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ hovernuclTP }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
         HOVERGEN - Release 45 (Jan 22 2004) Last Updated: Jan 22, 2004\\
844,876,418 bases; 300,108 sequences; 757,209 subseqs; 97,608 refers.\\
                                                                               \\
                       Vertebrate (chordata)\\
             Genomic data from EMBL Release 77  (December 2003)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  535 \\
3'NCR  &  .3F  3'-non coding region  &  170,566 \\
5'INT  &  .5I 5'intron  &  1,381 \\
5'NCR  &  .5F  5'-non coding region  &  159,238 \\
CDS  &  .PE protein coding region  &  274,599 \\
ID  &  EMBL sequence data library entry  &  210,301 \\
INT\_INT  &  .IN  internal intron  &  132,033 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  164 \\
RRNA  &  .RR ribosomal RNA coding region  &  2,426 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  9 \\
SNRNA  &  .SN small nuclear RNA coding region  &  41 \\
TRNA  &  .TR transfer RNA coding region  &  35,309 \\
\hline
 & Total: & 986,602 \\
\hline \hline
\end{tabular}

\section{ trypano }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
         trypano Rel. 1 (27 Janvier 2004) Last Updated: Jan 27, 2004\\
117,177,046 bases; 158,838 sequences; 4,744 subseqs; 2,114 refers.\\
	Genomic data from GenBank Rel. 139 (15 December 2003)\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
LOCUS  &  sequenced DNA fragment  &  157,983 \\
CDS  &  .PE protein coding region  &  5,137 \\
TRNA  &  .TR transfer RNA coding region  &  38 \\
RRNA  &  .RR ribosomal RNA coding region  &  206 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  192 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  26 \\
\hline
 & Total: & 163,582 \\
\hline \hline
\end{tabular}

\section{ ensembl24 }
\textbf{Bank details}
            ****     ACNUC Data Base Content      ****  \\
	     Ensembl databases rel 24\\
             Ensembl bee  Genome rel 24 - Arnel1.1 (Oct 2004)\\
             Ensembl cbriggsae  Genome rel 24 - cb25.agp8 (Oct 2004)\\
             Ensembl celegans  Genome rel 24 - WS 116 (Oct 2004)\\
             Ensembl chicken  Genome rel 24 - WASHUC1 (Oct 2004)\\
             Ensembl fruitfly  Genome rel 24 - DBGP3.1 (Oct 2004)\\
             Ensembl fugu  Genome rel 24 - Fugu v2.0 (Oct 2004)\\
             Ensembl human  Genome rel 24 - NCBI34 (Oct 2004)\\
             Ensembl mosquito  Genome rel 24 - MOZ 2 (Oct 2004)\\
             Ensembl mouse  Genome rel 24 - NCBI m33 (Oct 2004)\\
             Ensembl rat  Genome rel 24 - RGSC 3.1 (Oct 2004)\\
             Ensembl tetraodon  Genome rel 24 - TETRAODON7 (Oct 2004)\\
             Ensembl zebrafish  Genome rel 24 - WTSI Zv4 (Oct 2004)\\
             Ensembl chimp  Genome rel 24 - CHIMP1 (Oct 2004)\\
	     Ensembl dog  Genome rel 27 - BROADD1 (Dec 2004)\\
   warning : cds located on contigs were removed\\
19,025,147,322 bases; 70,063 sequences; 3,329,559 subseqs; 0 refers.

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  103,418 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  185,154 \\
CDS  &  .PE protein coding region  &  345,875 \\
ID  &  EMBL sequence data library entry  &  70,063 \\
INT\_INT  &  .IN  internal intron  &  2,328,941 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  20,425 \\
MRNA  &  .RN mRNA  &  345,746 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 3,399,622 \\
\hline \hline
\end{tabular}

\section{ ensembl34 }
\textbf{Bank details}
            ****     ACNUC Data Base Content      ****   \\
                 Ensembl databases release 34        \\
Espece                                   \#CDS(1)/STOP(2)/N(3)/miss(4)\\
Apis mellifera                          27736/1/269 (0\%/0\%/0\%)\\
Caenorhabditis briggsae                 14712/0/23 (0\%/0\%/0\%)\\
Caenorhabditis elegans                  25797/1/0 (0\%/0\%/0\%)\\
Gallus gallus                           28392/20/298 (0\%/1\%/0\%)\\
Pan troglodytes                         39538/6129/770 (15\%/1\%/0\%)\\
Ciona intestinalis                      21574/0/58 (0\%/0\%/0\%)\\
Bos taurus                              32647/7/617 (0\%/1\%/0\%)\\
Canis familiaris                        29998/0/0 (0\%/0\%/1\%)\\
Drosophila melanogaser                  19350/18/1 (0\%/0\%/0\%)\\
Fugu rubripes                           22099/0/283 (0\%/1\%/0\%)\\
Homo sapiens                            36919/48/24 (0\%/0\%/2\%)\\
Macaca mulatta                          31370/94/8360 (0\%/26\%/0\%)\\
Anopheles gambiae                       15799/0/19 (0\%/0\%/0\%)\\
Mus musculus                            35075/36/60 (0\%/0\%/1\%)\\
Monodelphis domestica                   13249/0/59 (0\%/0\%/0\%)\\
Rattus norvegicus                       32241/25/607 (0\%/1\%/2\%)\\
Tetraodon nigroviridis                  16275/1/233 (0\%/1\%/0\%)\\
Xenopus tropicalis                      52684/1/906 (0\%/1\%/0\%)\\
Saccharomyces cerevisiae                6680/22/0 (0\%/0\%/0\%)\\
Danio rerio                             32109/0/281 (0\%/0\%/0\%)\\
1:\# of CDS;2:CDS with internal stop;3:CDS with undetermined codon;4:missing CDS\\
   warning : cds located on contigs were removed\\
29,605,509,937 bases; 368,619 sequences; 5,302,323 subseqs; 0 refers.\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  156,270 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  280,705 \\
CDS  &  .PE protein coding region  &  534,246 \\
ID  &  EMBL sequence data library entry  &  368,619 \\
INT\_INT  &  .IN  internal intron  &  3,763,554 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  33,511 \\
MRNA  &  .RN mRNA  &  534,037 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 5,670,942 \\
\hline \hline
\end{tabular}

\section{ ensembl41 }
\textbf{Bank details}
            ****     ACNUC Data Base Content      ****   \\
                 Ensembl databases release 41        \\
Espece                                  Release/\#CDS(1)/STOP(2)/N(3)/miss(4)\\
Aedes aegypti                           41\_1a 11360/0/2/0 (0\%/0\%/0\%)\\
Anopheles gambiae                       41\_3d 13510/0/31/0 (0\%/0\%/0\%)\\
Apis mellifera                          38\_2d 27755/1/269/0 (0\%/0\%/0\%)\\
Bos taurus                              41\_2 32556/7/620/12 (0\%/1\%/0\%)\\
Caenorhabditis elegans                  41\_160 25218/1/0/0 (0\%/0\%/0\%)\\
Canis familiaris                        41\_1j 29813/0/0/0 (0\%/0\%/0\%)\\
Caenorhabditis briggsae                 25 14712/0/23/1 (0\%/0\%/0\%)\\
Ciona intestinalis                      41\_2c 20000/0/128/0 (0\%/0\%/0\%)\\
Ciona savignyi                          41\_2b 20150/1/27/0 (0\%/0\%/0\%)\\
Danio rerio                             41\_6b 36065/5/361/0 (0\%/1\%/0\%)\\
Dasypus novemcinctus                    40\_1 13567/12/8857/0 (0\%/65\%/0\%)\\
Drosophila melanogaster                 41\_43 19577/33/1/0 (0\%/0\%/0\%)\\
Echinops telfairi                       40\_1 14309/8/9348/0 (0\%/65\%/0\%)\\
Gallus gallus                           41\_1p 20667/13/455/0 (0\%/2\%/0\%)\\
Gasterosteus aculeatus                  41\_1a 27181/13/138/0 (0\%/0\%/0\%)\\
Homo sapiens                            41\_36c 47004/41/6/0 (0\%/0\%/0\%)\\
Loxodonta africana                      40\_1 14366/10/9618/0 (0\%/66\%/0\%)\\
Macaca mulatta                          41\_10a 36446/14/491/0 (0\%/1\%/0\%)\\
Monodelphis domestica                   41\_3a 30358/0/80/0 (0\%/0\%/0\%)\\
Mus musculus                            41\_36b 29026/34/2/0 (0\%/0\%/0\%)\\
Oryctolagus cuniculus                   41\_1a 13705/4/8615/0 (0\%/62\%/0\%)\\
Oryzias latipes                         41\_1 25880/0/546/0 (0\%/2\%/0\%)\\
Pan troglodytes                         41\_21 32667/4/739/0 (0\%/2\%/0\%)\\
Rattus norvegicus                       41\_34k 32996/34/686/0 (0\%/2\%/0\%)\\
Saccharomyces cerevisiae                41\_1d 4767/2/0/0 (0\%/0\%/0\%)

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  188,480 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  485,916 \\
CDS  &  .PE protein coding region  &  659,922 \\
ID  &  EMBL sequence data library entry  &  742,978 \\
INT\_INT  &  .IN  internal intron  &  4,342,137 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  54,036 \\
MRNA  &  .RN mRNA  &  659,922 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 7,133,391 \\
\hline \hline
\end{tabular}

\section{ ensembl47 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****\\
Ensembl Release 47	     		 Last Updated: Dec 12, 2007\\
76,798,685,993 bases; 3,138,133 sequences; 8,132,077 subseqs; 0 refers.\\
 Tetraodon nigroviridis - Release 47\_1i \\
 Oryzias latipes - Release 47\_1c \\
 Homo sapiens - Release 47\_36i \\
 Mus musculus - Release 47\_37 \\
 Rattus norvegicus - Release 47\_34q \\
 Pan troglodytes - Release 47\_21f \\
 Macaca mulatta - Release 47\_10f \\
 Aedes aegypti - Release 47\_1a \\
 Anopheles gambiae - Release 47\_3i \\
 Bos taurus - Release 47\_3d \\
 Caenorhabditis elegans - Release 47\_180 \\
 Canis familiaris - Release 47\_2e \\
 Cavia porcellus - Release 47\_1b \\
 Ciona intestinalis - Release 47\_2g \\
 Ciona savignyi - Release 47\_2e \\
 Dasypus novemcinctus - Release 47\_1d \\
 Drosophila melanogaster - Release 47\_43b \\
 Echinops telfairi - Release 47\_1d \\
 Erinaceus europaeus - Release 47\_1b \\
 Felis catus - Release 47\_1b \\
 Gallus gallus - Release 47\_2e \\
 Gasterosteus aculeatus - Release 47\_1d \\
 Loxodonta africana - Release 47\_1c \\
 Monodelphis domestica - Release 47\_5b \\
 Myotis lucifugus - Release 47\_1c \\
 Ornithorhynchus anatinus - Release 47\_1d \\
 Oryctolagus cuniculus - Release 47\_1d \\
 Otolemur garnettii - Release 47\_1a \\
 Saccharomyces cerevisiae - Release 47\_1g \\
 Sorex araneus - Release 47\_1a \\
 Spermophilus tridecemlineatus - Release 47\_1c \\
 Takifugu rubripes - Release 47\_4g \\
 Tupaia belangeri - Release 47\_1b \\
 Xenopus tropicalis - Release 47\_41g 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  272,454 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  717,743 \\
CDS  &  .PE protein coding region  &  788,657 \\
ID  &  EMBL sequence data library entry  &  3,138,133 \\
INT\_INT  &  .IN  internal intron  &  6,236,128 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  117,095 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 11,270,210 \\
\hline \hline
\end{tabular}

\section{ ensembl49 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****\\
             Ensembl Release 49	     		 Last Updated: Apr 23, 2008\\
90,338,630,754 bases; 3,499,715 sequences; 9,289,073 subseqs; 0 refers.\\
\\
 Aedes aegypti - Release 49\_1b \\
 Anopheles gambiae - Release 49\_3j \\
 Apis mellifera - Release 38\_2d \\
 Bos taurus - Release 49\_3f \\
 Caenorhabditis elegans - Release 49\_180a \\
 Canis familiaris - Release 49\_2g \\
 Cavia porcellus - Release 49\_1c \\
 Ciona intestinalis - Release 49\_2i \\
 Ciona savignyi - Release 49\_2f \\
 Danio rerio - Release 49\_7c \\
 Dasypus novemcinctus - Release 49\_1f \\
 Drosophila melanogaster - Release 49\_44 \\
 Echinops telfairi - Release 49\_1e \\
 Equus caballus - Release 49\_2 \\
 Erinaceus europaeus - Release 49\_1c \\
 Felis catus - Release 49\_1c \\
 Gallus gallus - Release 49\_2g \\
 Gasterosteus aculeatus - Release 49\_1f \\
 Homo sapiens - Release 49\_36k \\
 Loxodonta africana - Release 49\_1d \\
 Macaca mulatta - Release 49\_10h \\
 Microcebus murinus - Release 49\_1 \\
 Monodelphis domestica - Release 49\_5d \\
 Mus musculus - Release 49\_37b \\
 Myotis lucifugus - Release 49\_1e \\
 Ochotona princeps - Release 49\_1 \\
 Ornithorhynchus anatinus - Release 49\_1f \\
 Oryctolagus cuniculus - Release 49\_1f \\
 Oryzias latipes - Release 49\_1e \\
 Otolemur garnettii - Release 49\_1e \\
 Pan troglodytes - Release 49\_21h \\
 Pongo pygmaeus - Release 49\_1 \\
 Rattus norvegicus - Release 49\_34s \\
 Saccharomyces cerevisiae - Release 49\_1h \\
 Sorex araneus - Release 49\_1c \\
 Spermophilus tridecemlineatus - Release 49\_1e \\
 Takifugu rubripes - Release 49\_4i \\
 Tetraodon nigroviridis - Release 49\_1k \\
 Tupaia belangeri - Release 49\_1d \\
 Xenopus tropicalis - Release 49\_41i \\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  307,441 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  800,830 \\
CDS  &  .PE protein coding region  &  892,572 \\
GENE  &  .GN gene  &  805,489 \\
ID  &  EMBL sequence data library entry  &  3,499,715 \\
INT\_INT  &  .IN  internal intron  &  7,157,683 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  130,547 \\
MRNA  &  .MR mRNA  &  892,572 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 14,486,849 \\
\hline \hline
\end{tabular}

\section{ macaca45 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
Ensembl - Macaca mulatta - Release 45\_10e - (11 Sep 2007) Last Updated: Sep 11, 2007\\
3,053,326,321 bases; 94,529 sequences; 194,187 subseqs; 0 refers.\\
MENU Nber of lines= 21                                                         

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  6,058 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  13,894 \\
CDS  &  .PE protein coding region  &  36,227 \\
ID  &  EMBL sequence data library entry  &  94,529 \\
INT\_INT  &  .IN  internal intron  &  132,745 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  5,263 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 288,716 \\
\hline \hline
\end{tabular}

\section{ dog45 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
       Ensembl Canis familiaris  (Rel. 45\_2c) Last Updated: Jul  4, 2007\\
2,531,673,731 bases; 2,585 sequences; 29,227 subseqs; 0 refers.\\
Software by M. Gouy, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  0 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  0 \\
CDS  &  .PE protein coding region  &  25,559 \\
ID  &  EMBL sequence data library entry  &  2,585 \\
INT\_INT  &  .IN  internal intron  &  0 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  3,668 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 31,812 \\
\hline \hline
\end{tabular}

\section{ dog47 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
Ensembl - Canis familiaris - Release 47\_2e - (16 Nov 2007) Last Updated: Nov 16, 2007\\
2,531,672,953 bases; 2,585 sequences; 285,811 subseqs; 0 refers.

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  8,923 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  23,273 \\
CDS  &  .PE protein coding region  &  25,559 \\
ID  &  EMBL sequence data library entry  &  2,585 \\
INT\_INT  &  .IN  internal intron  &  223,971 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  4,085 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 288,396 \\
\hline \hline
\end{tabular}

\section{ equus49 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
Ensembl - Equus caballus - Release 49\_2 - (2 Apr 2008) Last Updated: Apr  2, 2008\\
2,500,873,361 bases; 12,078 sequences; 268,341 subseqs; 0 refers.\\
MENU Nber of lines= 21                                                         

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  8,479 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  22,102 \\
CDS  &  .PE protein coding region  &  22,749 \\
ID  &  EMBL sequence data library entry  &  12,078 \\
INT\_INT  &  .IN  internal intron  &  210,568 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  4,443 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 280,419 \\
\hline \hline
\end{tabular}

\section{ pongo49 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
Ensembl - Pongo pygmaeus - Release 49\_1 - (16 Apr 2008) Last Updated: Apr 16, 2008\\
3,441,147,290 bases; 3,547 sequences; 249,306 subseqs; 0 refers.\\
MENU Nber of lines= 21                                                         

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  9,727 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  22,150 \\
CDS  &  .PE protein coding region  &  23,303 \\
ID  &  EMBL sequence data library entry  &  3,547 \\
INT\_INT  &  .IN  internal intron  &  191,652 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  2,474 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 252,853 \\
\hline \hline
\end{tabular}

\section{ rattus49 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
Ensembl - Rattus norvegicus - Release 49\_34s - (16 Apr 2008) Last Updated: Apr 16, 2008\\
2,718,897,321 bases; 2,793 sequences; 343,303 subseqs; 0 refers.\\
MENU Nber of lines= 21                                                         

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  12,122 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  29,343 \\
CDS  &  .PE protein coding region  &  32,948 \\
ID  &  EMBL sequence data library entry  &  2,793 \\
INT\_INT  &  .IN  internal intron  &  264,210 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  4,680 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 346,096 \\
\hline \hline
\end{tabular}

\section{ mouse38 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
          Ensembl Mus musculus (Rel.38\_35) Last Updated: Jul  6, 2007\\
2,676,276,909 bases; 7,505 sequences; 35,002 subseqs; 0 refers.\\
Software by M. Gouy, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  0 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  0 \\
CDS  &  .PE protein coding region  &  31,984 \\
ID  &  EMBL sequence data library entry  &  7,505 \\
INT\_INT  &  .IN  internal intron  &  0 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  3,018 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 42,507 \\
\hline \hline
\end{tabular}

\section{ homolens4 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****\\
   HOMOLENS 4 - Homologous genes from Ensembl(49)	 Last Updated: Jul  4, 2008\\
247,930,199 bases; 529 sequences; 64,224 subseqs; 206 refers.\\
\\
 Aedes aegypti - Release 49\_1b \\
 Anopheles gambiae - Release 49\_3j \\
 Apis mellifera - Release 38\_2d \\
 Bos taurus - Release 49\_3f \\
 Caenorhabditis elegans - Release 49\_180a \\
 Canis familiaris - Release 49\_2g \\
 Cavia porcellus - Release 49\_1c \\
 Ciona intestinalis - Release 49\_2i \\
 Ciona savignyi - Release 49\_2f \\
 Danio rerio - Release 49\_7c \\
 Dasypus novemcinctus - Release 49\_1f \\
 Drosophila melanogaster - Release 49\_44 \\
 Echinops telfairi - Release 49\_1e \\
 Equus caballus - Release 49\_2 \\
 Erinaceus europaeus - Release 49\_1c \\
 Felis catus - Release 49\_1c \\
 Gallus gallus - Release 49\_2g \\
 Gasterosteus aculeatus - Release 49\_1f \\
 Homo sapiens - Release 49\_36k \\
 Loxodonta africana - Release 49\_1d \\
 Macaca mulatta - Release 49\_10h \\
 Microcebus murinus - Release 49\_1 \\
 Monodelphis domestica - Release 49\_5d \\
 Mus musculus - Release 49\_37b \\
 Myotis lucifugus - Release 49\_1e \\
 Ochotona princeps - Release 49\_1 \\
 Ornithorhynchus anatinus - Release 49\_1f \\
 Oryctolagus cuniculus - Release 49\_1f \\
 Oryzias latipes - Release 49\_1e \\
 Otolemur garnettii - Release 49\_1e \\
 Pan troglodytes - Release 49\_21h \\
 Pongo pygmaeus - Release 49\_1 \\
 Rattus norvegicus - Release 49\_34s \\
 Saccharomyces cerevisiae - Release 49\_1h \\
 Sorex araneus - Release 49\_1c \\
 Spermophilus tridecemlineatus - Release 49\_1e \\
 Takifugu rubripes - Release 49\_4i \\
 Tetraodon nigroviridis - Release 49\_1k \\
 Tupaia belangeri - Release 49\_1d \\
 Xenopus tropicalis - Release 49\_41i \\


\textbf{Type names}
There are no subsequence type in this database
\section{ homolens4dna }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****\\
         HOMOLENS 4 - Homologous genes from Ensembl(49)	Last Updated: Jul  4, 2008\\
55,129,547,735 bases; 178,069 sequences; 9,247,193 subseqs; 0 refers.\\
\\
 Aedes aegypti - Release 49\_1b \\
 Anopheles gambiae - Release 49\_3j \\
 Apis mellifera - Release 38\_2d \\
 Bos taurus - Release 49\_3f \\
 Caenorhabditis elegans - Release 49\_180a \\
 Canis familiaris - Release 49\_2g \\
 Cavia porcellus - Release 49\_1c \\
 Ciona intestinalis - Release 49\_2i \\
 Ciona savignyi - Release 49\_2f \\
 Danio rerio - Release 49\_7c \\
 Dasypus novemcinctus - Release 49\_1f \\
 Drosophila melanogaster - Release 49\_44 \\
 Echinops telfairi - Release 49\_1e \\
 Equus caballus - Release 49\_2 \\
 Erinaceus europaeus - Release 49\_1c \\
 Felis catus - Release 49\_1c \\
 Gallus gallus - Release 49\_2g \\
 Gasterosteus aculeatus - Release 49\_1f \\
 Homo sapiens - Release 49\_36k \\
 Loxodonta africana - Release 49\_1d \\
 Macaca mulatta - Release 49\_10h \\
 Microcebus murinus - Release 49\_1 \\
 Monodelphis domestica - Release 49\_5d \\
 Mus musculus - Release 49\_37b \\
 Myotis lucifugus - Release 49\_1e \\
 Ochotona princeps - Release 49\_1 \\
 Ornithorhynchus anatinus - Release 49\_1f \\
 Oryctolagus cuniculus - Release 49\_1f \\
 Oryzias latipes - Release 49\_1e \\
 Otolemur garnettii - Release 49\_1e \\
 Pan troglodytes - Release 49\_21h \\
 Pongo pygmaeus - Release 49\_1 \\
 Rattus norvegicus - Release 49\_34s \\
 Saccharomyces cerevisiae - Release 49\_1h \\
 Sorex araneus - Release 49\_1c \\
 Spermophilus tridecemlineatus - Release 49\_1e \\
 Takifugu rubripes - Release 49\_4i \\
 Tetraodon nigroviridis - Release 49\_1k \\
 Tupaia belangeri - Release 49\_1d \\
 Xenopus tropicalis - Release 49\_41i \\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  307,441 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  800,830 \\
CDS  &  .PE protein coding region  &  892,572 \\
ID  &  EMBL sequence data library entry  &  178,069 \\
INT\_INT  &  .IN  internal intron  &  7,157,683 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  88,667 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 9,425,262 \\
\hline \hline
\end{tabular}

\section{ hoppsigen }
\textbf{Bank details}
NA

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
ID  &  EMBL sequence data library entry  &  9,757 \\
CDS  &  .PE protein coding region  &  3,814 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
CDE  &  .PS  &  9,757 \\
PPGENE  &  .PP  &  9,757 \\
3'FL  &  .3F  &  3,656 \\
5'FL  &  .5F  &  730 \\
DIRECT\_REPEAT  &  .DR  &  15,592 \\
REPEAT\_REGION  &  .RR  &  133,215 \\
POLYA\_REGION  &  .PA  &  1,694 \\
FL\_REPEAT  &  .FR  &  0 \\
\hline
 & Total: & 187,972 \\
\hline \hline
\end{tabular}

\section{ nurebnucl }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
         Nurebase 4.0 (26 September 2003) Last Updated: NOV 27, 2003\\
2,356,663 bases; 664 sequences; 518 subseqs; 787 refers.\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
CDS  &  .PE protein coding region  &  767 \\
ID  &  EMBL sequence data library entry  &  415 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  0 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 1,182 \\
\hline \hline
\end{tabular}

\section{ nurebprot }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
         Nurebase 4.0 (26 September 2003) Last Updated: NOV 27, 2003\\
          277,024 amino acids; 525 sequences; 634 references.\\
Software by M. Gouy \& M. Jacobzone, Laboratoire de biometrie, Universite Lyon I 

\textbf{Type names}
There are no subsequence type in this database
\section{ hogendnucl }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
  HOGENOM - genomic data - Release 03 (Oct 14 2005) Last Updated: Nov  7, 2005\\
2,538,433,251 bases; 227,950 sequences; 4,136,134 subseqs; 82,281 refers.\\
                                                                               \\
                        Fully Sequenced Organisms\\
   Protein data from http://www.ebi.ac.uk/proteome/ (August, 2005)\\
          Genomic data from GenomeReview  (June 2005) \\
                  and  EMBL (June 2005)\\
	   ( 263 fully sequenced organisms)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
ID  &  EMBL sequence data library entry  &  204,502 \\
CDS  &  .PE protein coding region  &  1,060,241 \\
TRNA  &  .TR transfer RNA coding region  &  49,216 \\
RRNA  &  .RR ribosomal RNA coding region  &  5,813 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  861 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  29 \\
SNRNA  &  .SN small nuclear RNA coding region  &  459 \\
3'INT  &  .3I 3'intron  &  309 \\
3'NCR  &  .3F  3'-non coding region  &  1,247,297 \\
5'INT  &  .5I 5'intron  &  1,263 \\
5'NCR  &  .5F  5'-non coding region  &  1,158,238 \\
INT\_INT  &  .IN  internal intron  &  635,856 \\
\hline
 & Total: & 4,364,084 \\
\hline \hline
\end{tabular}

\section{ hogendprot }
\textbf{Bank details}
               ****     ACNUC Data Base Content      ****                      \\
  HOGENOM - protein data - Release 03 (Oct 14 2005) Last Updated: Mar 10, 2006\\
          339,891,443 amino acids; 950,216 sequences; 92,805 references.\\
                                                                               \\
                        Fully Sequenced Organisms\\
   Protein data from http://www.ebi.ac.uk/proteome/ (August 2005)\\
	            ( 263 fully sequenced organisms)\\
\\
Retrieval software by M. Gouy \& M. Jacobzone, Lab. de Biometrie, UCB Lyon.\\
Data maintenance: L. Duret \& S. Penel\\
\\
Laboratoire de Biometrie et Biologie Evolutive\\
UMR CNRS 5558, Universite Claude Bernard - Lyon 1 \\
43, bd du 11 Novembre 1918 F-69622 Villeurbanne Cedex\\


\textbf{Type names}
There are no subsequence type in this database
\section{ genomicro1 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
              Genomicro1 (15 June 2006) Last Updated: Jul  6, 2006\\
10,758,321,631 bases; 203,021 sequences; 1,870,190 subseqs; 0 refers.\\
Software by M. Gouy, Lab. Biometrie et Biologie Evolutive, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'NCR  &  .3F  3'-non coding region  &  34,406 \\
5'NCR  &  .5F  5'-non coding region  &  84,333 \\
CDS  &  .PE protein coding region  &  91,991 \\
EXON  &  .EX exon  &  545,221 \\
GENE  &  .GE gene  &  74,019 \\
ID  &  EMBL sequence data library entry  &  203,020 \\
INT\_INT  &  .IN  internal intron  &  531,587 \\
MISC\_FEATURE  &  .MF misc feature  &  397,178 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  19,549 \\
MRNA  &  .MA mrna  &  91,907 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 2,073,211 \\
\hline \hline
\end{tabular}

\section{ genomicro2 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
              Genomicro (15 June 2006) Last Updated: Jul  6, 2006\\
9,997,088,008 bases; 326 sequences; 3,190,175 subseqs; 37 refers.\\
Software by M. Gouy, Lab. Biometrie et Biologie Evolutive, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'NCR  &  .3F  3'-non coding region  &  160,823 \\
5'NCR  &  .5F  5'-non coding region  &  224,530 \\
CDS  &  .PE protein coding region  &  263,070 \\
EXON  &  .EX exon  &  818,981 \\
GENE  &  .GE gene  &  95,967 \\
ID  &  EMBL sequence data library entry  &  324 \\
INT\_INT  &  .IN  internal intron  &  1,022,519 \\
MISC\_FEATURE  &  .MF misc feature  &  448,347 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  17,954 \\
MRNA  &  .MA mrna  &  134,149 \\
RRNA  &  .RR ribosomal RNA coding region  &  756 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  3,081 \\
\hline
 & Total: & 3,190,501 \\
\hline \hline
\end{tabular}

\section{ genomicro3 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
              Genomicro (15 June 2006) Last Updated: Jul  6, 2006\\
12,273,770,623 bases; 20,045 sequences; 2,850,395 subseqs; 0 refers.\\
Software by M. Gouy, Lab. Biometrie et Biologie Evolutive, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'NCR  &  .3F  3'-non coding region  &  58,936 \\
5'NCR  &  .5F  5'-non coding region  &  119,457 \\
CDS  &  .PE protein coding region  &  134,149 \\
EXON  &  .EX exon  &  818,981 \\
GENE  &  .GE gene  &  95,967 \\
ID  &  EMBL sequence data library entry  &  20,043 \\
INT\_INT  &  .IN  internal intron  &  1,022,457 \\
MISC\_FEATURE  &  .MF misc feature  &  448,347 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  17,954 \\
MRNA  &  .MA mrna  &  134,149 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 2,870,440 \\
\hline \hline
\end{tabular}

\section{ genomicro4 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
              Genomicro (15 June 2006) Last Updated: Jul  6, 2006\\
1,545,295,735 bases; 54,529 sequences; 0 subseqs; 0 refers.\\
Software by M. Gouy, Lab. Biometrie et Biologie Evolutive, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'NCR  &  .3F  3'-non coding region  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  0 \\
CDS  &  .PE protein coding region  &  0 \\
EXON  &  .EX exon  &  0 \\
GENE  &  .GE gene  &  0 \\
ID  &  EMBL sequence data library entry  &  54,529 \\
INT\_INT  &  .IN  internal intron  &  0 \\
MISC\_FEATURE  &  .MF misc feature  &  0 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  0 \\
MRNA  &  .MA mrna  &  0 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 54,529 \\
\hline \hline
\end{tabular}

\section{ dickeya }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
    Dickeya dadantii 3937 Chromosome(Geb 2, 2009) Last Updated: Feb  2, 2009\\
4,922,802 bases; 1 sequences; 4,725 subseqs; 0 refers.\\
Software by M. Gouy, Lab. Biometrie et Biologie Evolutive, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  0 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  0 \\
CDS  &  .PE protein coding region  &  4,609 \\
INT\_INT  &  .IN  internal intron  &  0 \\
LOCUS  &  sequenced DNA fragment  &  1 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  19 \\
RRNA  &  .RR ribosomal RNA coding region  &  22 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  75 \\
\hline
 & Total: & 4,726 \\
\hline \hline
\end{tabular}

\section{ tetra53 }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
   Tetraodon negroviritis - Release 53 - (03/06/09) Last Updated: Mar  6, 2009\\
358,618,246 bases; 375 sequences; 316,244 subseqs; 0 refers.\\
MENU Nber of lines= 21                                                         

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  6,974 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  21,769 \\
CDS  &  .PE protein coding region  &  23,118 \\
ID  &  EMBL sequence data library entry  &  375 \\
INT\_INT  &  .IN  internal intron  &  240,437 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  828 \\
MRNA  &  .MR mRNA  &  23,118 \\
RRNA  &  .RR ribosomal RNA coding region  &  0 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  0 \\
TRNA  &  .TR transfer RNA coding region  &  0 \\
\hline
 & Total: & 316,619 \\
\hline \hline
\end{tabular}

\section{ trypanosoma }
\textbf{Bank details}
             ****     ACNUC Data Base Content      ****                         \\
Trypanosoma brucei - Chromosome 11 missing (Mar 30, 2009) Last Updated: Apr  3, 2009\\
20,527,385 bases; 10 sequences; 7,247 subseqs; 4 refers.\\
Software by M. Gouy, Lab. Biometrie et Biologie Evolutive, Universite Lyon I 

\textbf{Type names}
\noindent\begin{tabular}{llr}
\hline \hline
name & description & count \\
\hline
3'INT  &  .3I 3'intron  &  0 \\
3'NCR  &  .3F  3'-non coding region  &  0 \\
5'INT  &  .5I 5'intron  &  0 \\
5'NCR  &  .5F  5'-non coding region  &  0 \\
CDS  &  .PE protein coding region  &  7,089 \\
ID  &  EMBL sequence data library entry  &  10 \\
INT\_INT  &  .IN  internal intron  &  0 \\
MISC\_RNA  &  .RN other structural RNA coding region  &  28 \\
RRNA  &  .RR ribosomal RNA coding region  &  62 \\
SCRNA  &  .SC small cytoplasmic RNA coding region  &  0 \\
SNRNA  &  .SN small nuclear RNA coding region  &  5 \\
TRNA  &  .TR transfer RNA coding region  &  63 \\
\hline
 & Total: & 7,257 \\
\hline \hline
\end{tabular}\end{Schunk}


\section*{Session Informations}

\begin{scriptsize}

This part was compiled under the following \Rlogo{}~environment:

\begin{itemize}
  \item R version 2.9.0 (2009-04-17), \verb|i386-apple-darwin8.11.1|
  \item Locale: \verb|fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/C/C|
  \item Base packages: base, datasets, graphics, grDevices, grid,
    methods, stats, utils
  \item Other packages: ade4~1.4-11, ape~2.3, grImport~0.4-3,
    MASS~7.2-46, quadprog~1.4-11, seqinr~2.0-3, tseries~0.10-18,
    XML~2.3-0, xtable~1.5-5, zoo~1.5-5
  \item Loaded via a namespace (and not attached): gee~4.13-13,
    lattice~0.17-22, nlme~3.1-90
\end{itemize}
There were two compilation steps:

\begin{itemize}
  \item \Rlogo{} compilation time was: Thu Apr 23 13:09:25 2009
  \item \LaTeX{} compilation time was: \today
\end{itemize}

\end{scriptsize}

% END - DO NOT REMOVE THIS LINE

%%%%%%%%%%%%  BIBLIOGRAPHY %%%%%%%%%%%%%%%%%
\clearpage
\addcontentsline{toc}{section}{References}
\bibliographystyle{plain}
\bibliography{../config/book}
\end{document}
